batch_size: 16
patch_size: 256
downscaling_factor: 4.0
resolution_in_mpp: 0.0
slide_path: /home/saparia/Desktop/private/ml_challenge/slide_folder
save_path: /home/saparia/Desktop/private/ml_challenge/save_folder
model_path: /home/saparia/Desktop/private/ml_challenge/ctranspath.pth
file_extension: .svs
save_patch_images: False
save_tile_preview: False
preview_size: 4096
white_thresh: [170, 185, 175]
black_thresh: [0, 0, 0]
calc_thresh: [40, 40, 40]
invalid_ratio_thresh: 0.3
edge_threshold: 2
split: [0, 1]
exctraction_list: None
debug: True
